services:
  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: qdrant
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API
    volumes:
      - "./volumes/qdrant:/qdrant/storage:z"
  neo4j:
    image: neo4j:5.11.0
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP API
      - "7687:7687" # Bolt protocol
    volumes:
      - "./volumes/neo4j:/data"
